name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    environment: default

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${DOCKER_REPOSITORY}/${DOCKER_TAG}"
    - name: Login to Docker Repository
      run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD} ${DOCKER_REPOSITORY}
    - name: Push the Docker image
      run: docker push "${DOCKER_REPOSITORY}/${DOCKER_TAG}"
  
  deploy:
    needs: build
    runs-on: self-hosted
  
    steps:
    - uses: azure/setup-kubectl@v2.0
    - name: Deploy to Kubernetes
      run: kubectl --config /config/config rollout restart deployment/test-docs
